name: Triggering self-healing script if high-memory usage is detected
enabled: true
description: This workflow triggers a self-healing script to improve memory limits for pods in a critical usage status

triggers:
  - type: alert

#Tests script
steps:
  # Foreach loops iterate over arrays
  - name: query_high_memory_pods
    type: elasticsearch.esql.query
    with:
      query: FROM metrics-* | WHERE `kubernetes.pod.name` IS NOT NULL | WHERE NOT ((k8s.pod.name LIKE "*collector*") OR (k8s.pod.name LIKE "*gke*") OR (k8s.pod.name LIKE "*konnectivity*") OR (k8s.pod.name LIKE "*gmp*") OR (k8s.pod.name LIKE "*kube*") OR (k8s.pod.name LIKE "*pdcsi*") OR (k8s.pod.name LIKE "*metrics*") OR (k8s.pod.name LIKE "*l7*"))| WHERE @timestamp > NOW() - 1h| STATS memavg = AVG(metrics.k8s.container.memory_limit_utilization) BY k8s.deployment.name | WHERE memavg > 0.5
      format: json

  - name: loop_over_results
    type: foreach 
    foreach: "${{steps.query_high_memory_pods.output.values}}"
    steps:
      - name: process-item
        type: console
        with:
          message: "Executing remediation script  for deployment: {{foreach.item[1]}}"
      - name: call-remediation-script
        type: http
        with:
          url: http://34.170.33.80/increase-memory
          method: POST
          headers:
            Content-Type: application/json
          body:
            deployments:
              - "{{foreach.item[1]}}"